### ISSUE TITLE
2019.4 URP

### ISSUE THREAD

**Issue by stychu** [daniel-ilett/smo-shaders#1]
Hey there! Would it be possible for you to update this project to the newest LTS unity version (2019.4.17f1) ?? I have tried to run it in that version but nothing works. I really look into that Neon super Mario effect its really cool!!

**Comment by stychu** [comment]
It doesn't even work with the version in which it was done. :(
![Unity_kKIG3gUjPT](https://user-images.githubusercontent.com/9383657/104137846-178e3300-53a0-11eb-9566-503261bdc34c.png)

**Comment by daniel-ilett** [comment]
Hey! So, basically I only ever planned to make this effect run in the built-in pipeline and leave it there. Porting post process effects to URP is quite an involved task and requires re-writing a lot of code - as far as I'm aware, there's no easy way to write code that "just works" on both the built-in pipeline and URP. Once Unity officially supports custom PP on URP, it might get easier.

However, if you're interested in porting the effect yourself, there are ways to do that - this tutorial outlines how you might do it: https://cyangamedev.wordpress.com/2020/06/22/urp-post-processing/
